### ISSUE TITLE
支持 Duckduckgo AI 和 OpenRouter

### ISSUE THREAD

**Issue by FurryR** [wangyz1999/LiteLoaderQQNT-GPT-Reply#12]
Duckduckgo AI 和 OpenRouter 相比 OpenAI 提供了更多模型选择。

- Duckduckgo AI API 对非盈利项目完全免费，提供强隐私保障（不会使用输入作为训练数据、不跟踪），但国内不能正常访问
- OpenRouter 不需要用户配置 API 接口而只需跳转到官网登录，并且部分模型为免费使用

支持 Duckduckgo AI 和 OpenRouter 可以让更多用户在免费的情况下使用 ChatGPT 回复，并增强隐私保护。

**Comment by Crazy-FuQing** [comment]
作者大大能否支持下DeepSeek这个老好用了  跪求 @wangyz1999

**Comment by MarchPhantasia** [comment]
@wangyz1999 作者你好，我基于https://github.com/mumu-lhl/duckduckgo-ai-chat 以及 https://www.npmjs.com/package/fetch-event-stream?activeTab=code 做出了一个duckduckgo的ai回复示例，但目前存在一些prompt上的使用问题，以及我对上述的两个包都进行了不同程度的修改，想和您交流一下
![image](https://github.com/user-attachments/assets/2653329e-3794-4637-b778-ee9de6f4e25a)

**Comment by MarchPhantasia** [comment]
> @wangyz1999 作者你好，我基于https://github.com/mumu-lhl/duckduckgo-ai-chat 以及 https://www.npmjs.com/package/fetch-event-stream?activeTab=code 做出了一个duckduckgo的ai回复示例，但目前存在一些prompt上的使用问题，以及我对上述的两个包都进行了不同程度的修改，想和您交流一下 ![image](https://private-user-images.githubusercontent.com/161869772/385219516-2653329e-3794-4637-b778-ee9de6f4e25a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDc0NTksIm5iZiI6MTczMTQwNzE1OSwicGF0aCI6Ii8xNjE4Njk3NzIvMzg1MjE5NTE2LTI2NTMzMjllLTM3OTQtNDYzNy1iNzc4LWVlOWRlNmY0ZTI1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxMDI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTkxZDIzZjY0ZmQ1MjRiOTNhZGZjY2ZiOGFlZDZkZTUzM2YxMTMwN2Y0NmM4Y2ZmYjgwMDhlNzgxNDVkMTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PQQnCZT-JzJN7aaYkNUQEZkNzaTsuEps3Fyi6eGcTbY)

这个报错我已经解决了，是https://github.com/mumu-lhl/duckduckgo-ai-chat仓库有一处events相关的代码缺失了流输出的结束标志的判断语句，稍后我会向该仓库提交PR。

**Comment by MarchPhantasia** [comment]
> 作者大大能否支持下DeepSeek这个老好用了 跪求 @wangyz1999

你好，我查看了一下deepseek的文档，目前deepseek已经兼容了openAI的api规范，已经可以使用了

**Comment by MarchPhantasia** [comment]
> Duckduckgo AI 和 OpenRouter 相比 OpenAI 提供了更多模型选择。
> 
> * Duckduckgo AI API 对非盈利项目完全免费，提供强隐私保障（不会使用输入作为训练数据、不跟踪），但国内不能正常访问
> * OpenRouter 不需要用户配置 API 接口而只需跳转到官网登录，并且部分模型为免费使用
> 
> 支持 Duckduckgo AI 和 OpenRouter 可以让更多用户在免费的情况下使用 ChatGPT 回复，并增强隐私保护。

我已提交PR，支持了Duckduckgo AI，其中OpenRouter已经兼容了OpenAI的API，请查看官方文档中关于OpenAI API 的使用描述
![image](https://github.com/user-attachments/assets/8441290c-628a-4377-a9c5-1b76e0e7a91a)
![image](https://github.com/user-attachments/assets/cfcd2aad-2cbc-4917-86aa-166b1e8eaa79)

**Comment by wangyz1999** [comment]
Merged in #23
