### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by ToxiceOwO** [wangyz1999/LiteLoaderQQNT-GPT-Reply#14]
这个连接不会走http代理吗？昨天用的网络直接能连，就能用。今天用的不能连的网络挂了clash，卡在gpt思考中。

**Comment by StarXiaolin** [comment]
我开着clash，也卡在”GPT思考中...Error: Connection error.“

**Comment by wangyz1999** [comment]
如果网络能正常使用OpenAI接口就能用

不能用OpenAI的话可以用第三方的api服务
