### ISSUE TITLE
流式回复在处理并发请求时可能发生数据混淆

### ISSUE THREAD

**Issue by GladerJ** [wangyz1999/LiteLoaderQQNT-GPT-Reply#20]
![image](https://github.com/user-attachments/assets/333a05bb-7109-4b7b-baa9-b396830d1ba4)
如上图，我首先询问了“帮我解释一下什么是人工智能”，在生成的过程中点击取消，紧接着我再询问了“帮我制定一份学习计划”，此时发现生成的结果将这两次产生的结果混淆在了一起。
我尝试在本地的“main.js”代码中的用于“流式获取GPT回复”的函数中进行修改，思路是params中传入一个requestId，在发送响应时附带上这个requestId，前端可以通过该ID来识别各自请求的数据流。在测试时上述问题并未再出现，不知道是否还有更好地解决方式。期待您的更新。

**Comment by wangyz1999** [comment]
已修复

https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/releases/tag/v2.0.0
