### ISSUE TITLE
[功能请求]增加多个prompt预设+临时输入prompt功能

### ISSUE THREAD

**Issue by dangehub** [wangyz1999/LiteLoaderQQNT-GPT-Reply#22]
一般来说在群聊中使用LLM可能有以下几个场景：
1.回答问题
2.总结自己的口头发言，以更书面的形式发出去
3.翻译

目前只能预设一种prompt，很难同时应对多种场景。希望能增加一个多个预设的功能，效果大概如图：
![image](https://github.com/user-attachments/assets/00d085e6-b80d-4005-ada6-839b49fd3278)

如果能自定义GPT1、GPT2的名字就更好了。

更进阶来说，有时候临时有修改prompt的需求，如果能增加一个自定义GPT的选项，点开后弹出输入框，可以在这里临时修改prompt，那么泛用性会更高。

**Comment by wangyz1999** [comment]
https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/releases/tag/v2.0.0
