### ISSUE TITLE
DuckDuckGo AI Chat 模型的API接口填什么呢

### ISSUE THREAD

**Issue by nogodnodevil** [wangyz1999/LiteLoaderQQNT-GPT-Reply#26]
大佬，我想问要使用DuckDuckGo AI Chat 模型，API接口要填什么

**Comment by wangyz1999** [comment]
留为空就行

**Comment by nogodnodevil** [comment]
> 留为空就行

留空的话，不管开不开梯子都连接不上，如图。
![PixPin_2024-12-02_20-25-39](https://github.com/user-attachments/assets/0a94d5d7-5b17-4c9a-a74d-dd5e75547d40)

**Comment by wangyz1999** [comment]
[https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1](https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1)

你在这个网站能用吗？要不你把文件删了重新装下试试？我测试的可以正常用没法复刻这个错误，所以我也不知道是啥原因

**Comment by nogodnodevil** [comment]
> https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
> 
> 你在这个网站能用吗？要不你把文件删了重新装下试试？我测试的可以正常用没法复刻这个错误，所以我也不知道是啥原因

网站可以用，但是要挂梯子。
此外，使用DuckDuckGo AI Chat模型，它的API是从openai官网得到的是吧？

**Comment by wangyz1999** [comment]
不是openai官网，是这个 [https://github.com/mumu-lhl/duckduckgo-ai-chat](https://github.com/mumu-lhl/duckduckgo-ai-chat)

这个功能是这个人写的 [https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/pull/23](https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/pull/23)

**Comment by nogodnodevil** [comment]
明白了大佬，明天我再试试

**Comment by MarchPhantasia** [comment]
> 明白了大佬，明天我再试试

如果要使用的话，可以打开代理软件的TUN模式，将全部流量代理，目前暂且不知道怎么让这个接口走代理qwq

**Comment by MarchPhantasia** [comment]
> > > 明白了大佬，明天我再试试
> > 
> > 
> > 如果要使用的话，可以打开代理软件的TUN模式，将全部流量代理，目前暂且不知道怎么让这个接口走代理qwq
> 
> 哈哈哈，谢谢。不过算了，我太废了，看了看https://github.com/mumu-lhl/duckduckgo-ai-chat 没搞明白怎么获取API。。。

api在项目中的这一部分
![image](https://github.com/user-attachments/assets/ca5dbec6-5c7a-4da6-9a95-4d7772542f58)

**Comment by nogodnodevil** [comment]
> > > > 明白了大佬，明天我再试试
> > > 
> > > 
> > > 如果要使用的话，可以打开代理软件的TUN模式，将全部流量代理，目前暂且不知道怎么让这个接口走代理qwq
> > 
> > 
> > 哈哈哈，谢谢。不过算了，我太废了，看了看https://github.com/mumu-lhl/duckduckgo-ai-chat 没搞明白怎么获取API。。。
> 
> api在项目中的这一部分 ![image](https://private-user-images.githubusercontent.com/161869772/391765686-ca5dbec6-5c7a-4da6-9a95-4d7772542f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODgwNjEsIm5iZiI6MTczMzE4Nzc2MSwicGF0aCI6Ii8xNjE4Njk3NzIvMzkxNzY1Njg2LWNhNWRiZWM2LTVjN2EtNGRhNi05YTk1LTRkNzc3MjU0MmY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWQwMGE4ZmI2MjMxYmJhYjg4YzZiZjFlOTMwNjMzZjdhYmNhY2EwMDE4YTlkMGMwYTEzMjkzM2U5NDVlYjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aJQVFvE7n5vbxz3UDz81D0WgnQSbKRfRZbRGXJobjcU)

不是，我说的是API密钥，我现在用的openai官网的不行。

**Comment by MarchPhantasia** [comment]
> > > > > 明白了大佬，明天我再试试
> > > > 
> > > > 
> > > > 如果要使用的话，可以打开代理软件的TUN模式，将全部流量代理，目前暂且不知道怎么让这个接口走代理qwq
> > > 
> > > 
> > > 哈哈哈，谢谢。不过算了，我太废了，看了看https://github.com/mumu-lhl/duckduckgo-ai-chat 没搞明白怎么获取API。。。
> > 
> > 
> > api在项目中的这一部分 ![image](https://private-user-images.githubusercontent.com/161869772/391765686-ca5dbec6-5c7a-4da6-9a95-4d7772542f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODgwNjEsIm5iZiI6MTczMzE4Nzc2MSwicGF0aCI6Ii8xNjE4Njk3NzIvMzkxNzY1Njg2LWNhNWRiZWM2LTVjN2EtNGRhNi05YTk1LTRkNzc3MjU0MmY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWQwMGE4ZmI2MjMxYmJhYjg4YzZiZjFlOTMwNjMzZjdhYmNhY2EwMDE4YTlkMGMwYTEzMjkzM2U5NDVlYjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aJQVFvE7n5vbxz3UDz81D0WgnQSbKRfRZbRGXJobjcU)
> 
> 不是，我说的是API密钥，我现在用的openai官网的不行。

实际上使用duckduckgo的api是不需要密钥的，代码里面这一部分也没有使用密钥。上面提到的fetch error报错是因为网络环境。

**Comment by nogodnodevil** [comment]
> > > > > > 明白了大佬，明天我再试试
> > > > > 
> > > > > 
> > > > > 如果要使用的话，可以打开代理软件的TUN模式，将全部流量代理，目前暂且不知道怎么让这个接口走代理qwq
> > > > 
> > > > 
> > > > 哈哈哈，谢谢。不过算了，我太废了，看了看https://github.com/mumu-lhl/duckduckgo-ai-chat 没搞明白怎么获取API。。。
> > > 
> > > 
> > > api在项目中的这一部分 ![image](https://private-user-images.githubusercontent.com/161869772/391765686-ca5dbec6-5c7a-4da6-9a95-4d7772542f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODgwNjEsIm5iZiI6MTczMzE4Nzc2MSwicGF0aCI6Ii8xNjE4Njk3NzIvMzkxNzY1Njg2LWNhNWRiZWM2LTVjN2EtNGRhNi05YTk1LTRkNzc3MjU0MmY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWQwMGE4ZmI2MjMxYmJhYjg4YzZiZjFlOTMwNjMzZjdhYmNhY2EwMDE4YTlkMGMwYTEzMjkzM2U5NDVlYjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aJQVFvE7n5vbxz3UDz81D0WgnQSbKRfRZbRGXJobjcU)
> > 
> > 
> > 不是，我说的是API密钥，我现在用的openai官网的不行。
> 
> 实际上使用duckduckgo的api是不需要密钥的，代码里面这一部分也没有使用密钥。上面提到的fetch error报错是因为网络环境。

还真是，感谢大佬耐心解答。最后一个问题：TUN模式和全局模式一样吗？比如看b站也会消耗机场流量吗？

**Comment by MarchPhantasia** [comment]
> TUN模式和全局模式一样吗？
使用上没有明确的区别，实现上差异比较大。看b站的话是会消耗机场流量的，如果你使用的是clashverge，那么我建议将bilibili添加到代理的过滤名单中
![image](https://github.com/user-attachments/assets/49690db2-c264-49e3-a962-f2b346689e37)

![image](https://github.com/user-attachments/assets/7cb93a7d-36da-44f4-a419-071a3cf31c55)

**Comment by nogodnodevil** [comment]
> 使用上没有明确的区别，实现上差异比较大。看b站的话是会消耗机场流量的，如果你使用的是clashverge，那么我建议将bilibili添加到代理的过滤名单中 ![image](https://private-user-images.githubusercontent.com/161869772/391769332-49690db2-c264-49e3-a962-f2b346689e37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODkyMjQsIm5iZiI6MTczMzE4ODkyNCwicGF0aCI6Ii8xNjE4Njk3NzIvMzkxNzY5MzMyLTQ5NjkwZGIyLWMyNjQtNDllMy1hOTYyLWYyYjM0NjY4OWUzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzE3OGQ1YjQ0YzY4ZDE5MzdjMjQxOGE0ZDgwMjdjZGFlN2MwZDQzMTc4Y2JhNzBjYjIxMTlmODliYTU4MDZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jQhzJrvaP7bozdDCo83C-addlZVTOlGb0GtB4BzWlRA)
> 
> ![image](https://private-user-images.githubusercontent.com/161869772/391769378-7cb93a7d-36da-44f4-a419-071a3cf31c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODkyMjQsIm5iZiI6MTczMzE4ODkyNCwicGF0aCI6Ii8xNjE4Njk3NzIvMzkxNzY5Mzc4LTdjYjkzYTdkLTM2ZGEtNDRmNC1hNDE5LTA3MWEzY2YzMWM1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmVlZGE0NjI3MjNmZThmZTFlYjUwNjM1ODRjMzYxYjA4MjVjM2Q4OGE1MjZjOWZhZWU2M2Y1ZTIwMGIwYjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CgDFvibfzPgqaqOnle7U2TE6DxdSJeLrIz6QN0neke4)

好的，都明白了，感谢大佬！
