### ISSUE TITLE
可以支持下自定义api接口吗

### ISSUE THREAD

**Issue by kldhsh123** [wangyz1999/LiteLoaderQQNT-GPT-Reply#3]
emmm
可以支持下自定义api接口吗

**Comment by zilewang7** [comment]
我提了个 pr
[feat: support to configure api url #4](https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/pull/4)

**Comment by wangyz1999** [comment]
@kldhsh123 已支持

https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/releases/tag/v1.0.3
