### ISSUE TITLE
大佬，为什么用3.5模型还是提示我要充钱 

### ISSUE THREAD

**Issue by bingbaicai** [wangyz1999/LiteLoaderQQNT-GPT-Reply#6]
GPT思考中...
Error: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

**Comment by bingbaicai** [comment]
我试着用https://api.gpt.ge/这类网上的chatgptkey，他一直是在思考中，问了下客服说第三方客户端要咨询作者哈哈

**Comment by wangyz1999** [comment]
用API的话3.5模型也是要付费的哈，你那个报错就是说用的key对应的账号没充钱

这个插件用的就是官方的客户端

**Comment by wangyz1999** [comment]
你用的第三方API应该是要改自定义API地址的，不知道你改了没

**Comment by bingbaicai** [comment]
好的 周一我试试 感谢老大的细心解答哈🫡

**Comment by StarXiaolin** [comment]
> 用API的话3.5模型也是要付费的哈，你那个报错就是说用的key对应的账号没充钱
> 
> 这个插件用的就是官方的客户端

我用官方的key报：
“GPT思考中...
Error: Connection error.”
好像是没有连接上，怎么解决
