### ISSUE TITLE
正常使用但是报错

### ISSUE THREAD

**Issue by Einck0** [wangyz1999/LiteLoaderQQNT-GPT-Reply#8]
使用是正常的但是在回复时总是带报错Error: Cannot read properties of undefined (reading 'delta')
![image](https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/assets/91471683/49be0351-bf00-44f3-9b3e-8ec0420346ec)
![image](https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/assets/91471683/8adf84ec-b2be-42bc-9b20-078440dcbe3f)
GPT-Reply==v1.0.4

**Comment by wangyz1999** [comment]
https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/releases/tag/v1.0.5
